<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-723K5MEV" failures="2" tests="2" name="Login Test" time="40.935" errors="0" timestamp="2024-04-07T13:22:08 IST">
  <testcase classname="testcases.TC001_LoginValidationTest" name="test_Validate_LoginTest" time="21.923">
    <failure type="java.lang.AssertionError" message="Failed while validating Login expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed while validating Login expected [true] but found [false]
at testcases.TC001_LoginValidationTest.test_Validate_LoginTest(TC001_LoginValidationTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_Validate_LoginTest -->
  <testcase classname="testcases.TC002_ScheduleAppointmentTest" name="test_Validate_ScheduleAppointment" time="2.889">
    <failure type="java.lang.AssertionError" message="Failed while validating the appointment creation expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Failed while validating the appointment creation expected [false] but found [true]
at testcases.TC002_ScheduleAppointmentTest.test_Validate_ScheduleAppointment(TC002_ScheduleAppointmentTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_Validate_ScheduleAppointment -->
</testsuite> <!-- Login Test -->
